[[bin]]
name = "e-netscan-gui"
path = "src/gui.rs"
[[bin]]
name = "e-netscan"
path = "src/terminal.rs"

[workspace]
members = []

[dependencies]
e-libscanner = { version = "^0.1", default-features = false, features = [
    "full",
] }
e-utils = { version = "^0.1", features = ["std"], default-features = false }
futures-lite = "1.12.0"
once_cell = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.17"
log4rs = "^1.1.0"
chrono = "0.4"
# iced_wgpu supporting Vulkan, Metal and DX12
# iced = { version = "0.4", default-features = false, features = ["wgpu"] }
# iced_glow supporting OpenGL 2.1+ and OpenGL ES 2.0+
iced = { version = "0.4.2", default-features = false, features = ["glow"] }
iced_native = "0.5"
image = { version = "0.24.2", default-features = false, features = ["ico"] }
clipboard = "0.5"
dirs = "4.0.0"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"
winapi = { version = "0.3", features = ["winnt"] }

[package.metadata.winres]
OriginalFilename = "E-NETSCAN.EXE"
LegalCopyright = "Copyright © 2022 Eternal"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...' # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false
strip = false

[profile.release]
opt-level = "z"
debug = false
split-debuginfo = '...' # Platform-specific.
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false
strip = true
lto = true
panic = 'abort'
codegen-units = 1

[package]
name = "e-netscan"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.0"
build = "build.rs"
authors = ["Eternal <EternalNight996@gmail.com, EternalNightYeah2@yeah.net>"]
description = "A low level with fast network scan tools"
license-file = "GNU-LICENSE"
readme = "README.md"
repository = "https://github.com/EternalNight996/e-netscan"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
